### PR TITLE
add "run" to Command

### PR DESCRIPTION
**Pull request by kadefor**
```
(dev2)# cat aa.py
from terminal import Command, red

def show(cmd):
    """
    foo's subcommand run

    :parms cmd: foo command
    """

    if cmd.color:
        print(red('show'))
    else:
        print('show')

cmd_show = Command('show', 'show something', version='1.0.0', run=show)
cmd_show.option('-c, --color', 'disable or enable colors')

cmd_show2 = Command('show2', 'show2 something', version='1.0.1')
cmd_show2.option('-c, --color', 'disable or enable colors')
cmd_show2.run = show
(dev2)#
(dev2)# cat bb.py
from terminal import Command
from aa import cmd_show, cmd_show2

program = Command('foo', version='1.0.0')
program.action(cmd_show)
program.action(cmd_show2)

program.parse()
(dev2)#
(dev2)# python bb.py -h

  foo 1.0.0

  Usage: foo <command> [option]

  Options:

    -h, --help      output the help menu
    -V, --version   output the version number

  Commands:

    show            show something
    show2           show2 something

(dev2)# python bb.py show
show
(dev2)# python bb.py show -c
show
(dev2)# python bb.py show2
show
(dev2)# python bb.py show2 -c
show
(dev2)#
```

### CODE REVIEW

**Comment by kadefor** [comment]
本来 Command 就有一个 func 参数, 不知道再添加这个 "run" 有没有必要?

**Comment by lepture** [comment]
@kadefor `func` is what you need.

Using `decorator` power to create a subcommand:

``` py
program = Command('foo', version='1.0.0')

@program.action
def show1(color=False):
    '''
    description ....

    :param color: enable print in color
    '''
    if color:
        print red('show')
    else:
        print 'show'


# add show2....

program.parse()
```

**Comment by kadefor** [comment]
Thank you for your prompt reply!

But I don't know how to split subcommands into multiple files(modules).

**Comment by lepture** [comment]
@kadefor In your cases, pass the function to `func` instead of `run`. If you want to get the parent command:

``` py
mysubcommand = Command('show')

def my_action():
    if mysubcommand.color:
       # ...

mysubcommand._command_func = mysubcommand
```

But it is a little tricky, I will take it into consideration, will figure out a better API.

**Comment by lepture** [comment]
Or something like this:

``` py
def my_action(color=False):
    if color:
        pass

mysubcommand = Command('show', func=my_action)
```

**Comment by kadefor** [comment]
Thank you for your help.

It can do that. But, when define the function, we must figure out all options as the function's args, I think it is Inflexible.

when create the function, can I do like this?

``` py
def my_action(cmd):
    if cmd.color:
        pass
```

then, "program.py"

``` py
# import the "my_action"
cmd = Command('show')
cmd.option('--color', "color show, default: True")
# then, use a method to add the "my_action"
cmd.parse()
```

run:

``` bash
$ python program.py show
$ python program.py show --no-color    # the "--no-color" behavior like "func"
```

**Comment by lepture** [comment]
@kadefor Use the power of `kwargs`:

``` py
def my_action(color=False, **kwargs):
    pass
```

It won't raise. You only need to define what you need.

**Comment by kadefor** [comment]
@lepture Apologies for the delay.

It's awesome. Thank you very much!

I just need to change my example:

from:

``` py
def my_action(cmd):
    if cmd.color:
        pass
```

to:

``` py
def my_action(**cmd):
    if cmd.get('color'):
        pass
```

**Pull request closed without merging**
